name: shader_toy
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0'
  flutter: '>=3.6.0-13.0.pre'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.0+3
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  shaders:
    #- assets/shaders/noise_gradient.glsl
    #- assets/shaders/truchet_tiling.glsl
    #- assets/shaders/debug.glsl
    #- assets/shaders/noise_types.glsl
    #- assets/shaders/scattered_semicircles.glsl
    - assets/shaders/noise/white_noise.frag
    - assets/shaders/noise/white_noise_color.frag
    - assets/shaders/noise/white_noise_color_cell.frag
    - assets/shaders/voronoi/voronoi.frag
    - assets/shaders/voronoi/voronoi_time.frag

  uses-material-design: true