name: shader_toy
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.6.0-13.0.pre'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.0+3

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - assets/flutter-shaders/noise_gradient_fragment.glsl
    - assets/flutter-shaders/truchet_tiling.glsl
    - assets/flutter-shaders/debug.glsl
    - assets/flutter-shaders/noise_types_fragment.glsl

  uses-material-design: true