name: Release

on:
  push:
    tags:
      - release.*

jobs:
  build:
    strategy:
      matrix:
        config:
        - runs_on: ubuntu-latest
          name: linux-release
          pre_run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
          build: flutter config --enable-linux-desktop && flutter create --platforms=linux . && flutter build linux --release
          output: /linux/x64/release/bundle
        - runs_on: ubuntu-latest
          name: web-release
          pre_run: ""
          build: flutter create --platforms=web . && flutter build web --release
          output: /web
#        - runs_on: windows-latest
#          name: windows-release
#          pre_run: ""
#          build: flutter config --enable-windows-desktop && flutter create --platforms=windows . && flutter build windows
#          output: /windows/runner/Release
# TODO: Window runs are Building forever, probably since the addition of Simplex algorithm, check error source and generate bug.
# Anyways, this should be fixed before release
    runs-on: ${{ matrix.config.runs_on }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: ${{ matrix.config.pre_run }}
      - name: Build
        working-directory: ./flutter_effects_demo
        run: ${{ matrix.config.build }}
      - name: Archive Release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: ${{ github.workspace }}/${{ matrix.config.name }}.zip
          directory: ./flutter_effects_demo/build${{ matrix.config.output }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}
          path: ./${{ matrix.config.name }}.zip
      - name: Upload Web artifact
        uses: actions/upload-pages-artifact@v1
        if: ${{ matrix.config.name == 'web-release' }}
        with:
          path: ./flutter_effects_demo/build/web/


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux-release
      - uses: actions/download-artifact@master
        with:
          name: web-release
      # - uses: actions/download-artifact@master
      #   with:
      #     name: windows-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux-release.zip
            ./web-release.zip
          # ./windows-release.zip
          
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
